### PR TITLE
Update to 1.20.6

### PR DESCRIPTION
**Pull request by tobiichi3227**
#7
https://github.com/YukkuriLaboratory/FabPose/pull/8/files#diff-200b38667674f1145dfa0dc61b4c5c284693abda49f5a588dc15766914b0235dR116

### CODE REVIEW

**Comment by turtton** [comment]
Thank you for the PR. Before merging, I would like to request two additional changes:

- Please format the Kotlin code (execute the `formatKotlin` task in gradle).
- Fix the compilation errors occurring within the `servertest` source set.

**Comment by tobiichi3227** [comment]
Ok!
I will do this soon.

**Comment by tobiichi3227** [comment]
Sorry, I forgot lint code. :cry:

**Comment by turtton** [comment]
Thankyou!!!

**Pull request merged**
